name: gen_doc

on: [push]

jobs:
  teroshdl-doc:
    name: '📓 Docs'
    runs-on: ubuntu-latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
    - name: 'install'
      run: |
        git clone https://github.com/TerosTechnology/colibri.git
        cd colibri
        git checkout -b trs_doc origin/trs_doc
        sudo rm -rf /usr/local/bin/phantomjs
        sudo npm install -g .
        cd ..
        teroshdl-hdl-documenter -f teroshdl.trs -o html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: built_doc # The folder the action should deploy.