name: gen_doc

on:
  push:
    branches:
      - master

jobs:
  teroshdl-doc:
    name: '📓 Docs'
    runs-on: ubuntu-latest
    container:
      image: docker://terostech/colibri:latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
    - name: 'doc_gen'
      run: |
        teroshdl-hdl-documenter -f teroshdl.trs -o html
        apt install -y rsync

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: built_doc # The folder the action should deploy.