name: gen_doc

on:
  push:
    branches:
      - master

jobs:
  teroshdl-doc:
    name: '📓 Docs'
    runs-on: ubuntu-latest
    container:
      image: docker://terostech/colibri:latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
    - name: 'doc_gen'
      run: |
        teroshdl-hdl-documenter teroshdl-hdl-documenter -i gamma_project.yml --outpath ./teroshdl_doc --fsm --dep -s all -c all -p all --symbol_vhdl ! 
        apt install -y rsync

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: teroshdl_doc # The folder the action should deploy.