name: gen_doc

on: [push]

  teroshdl-doc:
    name: '📓 Docs'
    runs-on: ubuntu-latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
    - name: 'install'
      run: |
        git clone https://github.com/TerosTechnology/colibri.git
        cd colibri
        npm install -g .

    - name: '📤 Upload artifact: HTML and LaTeX'
      uses: actions/upload-artifact@master
      with:
        name: doc
        path: |
          doc/