name: Test_gamma

on: [push]

jobs:
  test-suites:
    runs-on: ubuntu-18.04
    container:
      image: docker://terostech/multi-simulator:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          pip3 install fxpmath
          pip3 install matplotlib
          pip3 install numpy
          cd tb/cocotb/gamma
          make
          cd ..
          cd gamma_top
          make
